SELECT DISTINCT * 
FROM students 
WHERE Gender='Male';

SELECT DISTINCT * 
FROM students 
WHERE AGE!=22;

SELECT DISTINCT * 
FROM students 
WHERE 120>ROLL AND ROLL>10;

SELECT DISTINCT * 
FROM students 
WHERE 120>ROLL OR ROLL>10;

SELECT DISTINCT * 
FROM students 
WHERE ROLL BETWEEN 101 AND 105;

SELECT DISTINCT * 
FROM students 
WHERE CITY IN ('DHAKA','RAJSHAHI','KHULNA');