SELECT DISTINCT * 
FROM students 
WHERE NAME LIKE 'S%'; -- STARTS WITH S

SELECT DISTINCT * 
FROM students 
WHERE NAME LIKE '%S'; -- ENDS WITH S

SELECT DISTINCT * 
FROM students 
WHERE NAME LIKE '%SAL%'; -- ENDS WITH S

SELECT DISTINCT * 
FROM students 
WHERE NAME LIKE '_A%'; -- SECOND KEY IS A